# Generated by Django 2.2.15 on 2020-08-17 15:53

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS intarray'),
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS acoustid'),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('fingerprint', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('cluster', models.UUIDField(db_index=True, null=True)),
                ('acoustid', models.JSONField(null=True)),
            ],
            options={
                'ordering': ('path',),
            },
        ),
        migrations.AddIndex(
            model_name='fingerprint',
            index=django.contrib.postgres.indexes.GinIndex(fastupdate=True, fields=['fingerprint'], gin_pending_list_limit=1000, name='fingerprint_fingerp_2edc08_gin'),
        ),
    ]
